image:
  tag: "local"
  pullPolicy: "Never"

service:
  type: NodePort

ingressClass:
  controller: "oidq.dev/s-ingress"

tcpProxy: []

proxy:
  maxBodySize: "4K"

configuration:
  tls:
    defaultTlsSecret: "s-ingress-tls"
  module:
    security:
      enforceHttps: true
