apiVersion: v1
kind: Service
metadata:
  name: {{ include "s-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "s-ingress.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    {{ $isNodePort := eq .Values.service.type "NodePort" }}
    {{- if .Values.proxy.http.enabled }}
      {{ $http := .Values.proxy.http }}
    - port: 80
      targetPort: http
      {{ if $isNodePort }}nodePort: {{ $http.nodePort }}{{ end }}
      protocol: TCP
      name: http
    {{ end }}
    {{- if .Values.proxy.https.enabled }}
      {{ $https := .Values.proxy.https }}
    - port: 443
      targetPort: https
      {{ if $isNodePort }}nodePort: {{ $https.nodePort }}{{ end }}
      protocol: TCP
      name: https
    {{ end }}
    {{- if .Values.proxy.quic.enabled }}
      {{ $quic := .Values.proxy.quic }}
    - name: quic
      {{ if $isNodePort }}nodePort: {{ $quic.nodePort }}{{ end }}
      protocol: UDP
      port: 443
      targetPort: quic
    {{ end }}
    {{- range .Values.tcpProxy }}
    - name: "{{ .name }}"
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .podPort }}
    {{- end }}
  selector:
    {{- include "s-ingress.selectorLabels" . | nindent 4 }}
